USE [master]
GO

/****** Object:  Database [ExamDB] ******/
CREATE DATABASE [ExamDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExamDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ExamDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExamDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ExamDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExamDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExamDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExamDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExamDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExamDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExamDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExamDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ExamDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExamDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExamDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExamDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExamDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExamDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExamDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExamDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExamDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ExamDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExamDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExamDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExamDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExamDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExamDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExamDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExamDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ExamDB] SET  MULTI_USER 
GO

ALTER DATABASE [ExamDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExamDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExamDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExamDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ExamDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ExamDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ExamDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ExamDB] SET  READ_WRITE 
GO


